config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'

  devise_for :users, path: :/, path_names: { sign_in: :login, sign_up: :signup, sign_out: :logout }

  get     '/help',    to: 'static_pages#help'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable #, :confirmable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size:         { less_than: 5.megabytes,
                                      message: "should be less than 5MB" }

  # Returns a resized image for display.
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #, :confirmable

  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                    WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    size          = options[:size]
    gravatar_id   = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url  = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    |The
    a<> href="https://www.railstutorial.org/" Ruby on Rails Tutorial
    |by
    a< href="https://www.michaelhartl.com/" Michael Hartl
  nav
    ul
      li
        = link_to "About",    about_path
      li
        = link_to "Contact",  contact_path
      li
        a href="https://news.railstutorial.org/" News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "sample app", root_path, id: "logo"
    nav
      .navbar-header
        button.navbar-toggle.collapsed data-toggle="collapse"                       \
                                        data-target="#bs-example-navbar-collapse-1" \
                                        aria-expanded="false" type="button"         \
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      ul.nav.navbar-nav.navbar-right.collapse.navbar-collapse
        #bs-example-navbar-collapse-1
          ul.nav.navbar-nav.navbar-right
            li= link_to "Home", root_path
            li= link_to "Help", help_path
            - if user_signed_in?
              li= link_to "Users", users_path
              li.dropdown
                a.dropdown-toggle data-toggle="dropdown" href="#"
                  | Account
                  b.caret
                ul.dropdown-menu
                  li= link_to "Profile", current_user
                  li= link_to "Settings", edit_user_registration_path(current_user)
                  - if current_user.admin
                    li.divider
                    li= link_to "Admin profile", 'http://localhost:3000/admin/login', target: '_blank'
                  li.divider
                  li
                    = link_to "Log out", destroy_user_session_path, method: :delete
            - else
              li= link_to "Log in", new_user_session_path

app/views/layouts/_shim.html.slim
/![if lt IE 9]
  | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
  | </script

app/views/layouts/application.html.slim
doctype html
html
  head
    title =full_title(yield(:title))
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/microposts/_micropost.html.slim
li id="micropost-#{micropost.id}"
  = link_to gravatar_for(micropost.user, size: 50), micropost.user
  span.user= link_to micropost.user.name, micropost.user
  span.content
    = micropost.content
    = image_tag micropost.display_image if micropost.image.attached?
  span.timestamp
    | Posted #{time_ago_in_words(micropost.created_at)} ago.
    - if current_user
      = link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" }

app/views/relationships/create.js.slim
| $("#follow_form").html("#{escape_javascript(render('users/unfollow'))}");
| $("#followers").html("#{@user.followers.count}");

app/views/relationships/destroy.js.slim
| $("#follow_form").html("#{escape_javascript(render('users/follow'))}");
| $("#followers").html("#{@user.followers.count}");

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      |The form contains&nbsp
      = pluralize(object.errors.count, "error")
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render @feed_items
  = will_paginate @feed_items, params: { controller: :static_pages, action: :home }

app/views/shared/_micropost_form.html.slim
= form_with(model: @micropost, local: true) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"
  span.image
    = f.file_field :image, accept: "image/jpeg,image/gif,image/png"
javascript:
  | $("#micropost_image").bind("change", function() {
    | const size_in_megabytes = this.files[0].size/1024/1024;
    | if (size_in_megabytes > 5) {
      | alert("Maximum file size is 5MB. Please choose a smaller file.");
      | $("#micropost_image").val("");
    | }
  | });

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  a href="#{following_user_path(@user)}"
    strong#following.stat
      = @user.following.count
    |following

  a href="#{followers_user_path(@user)}"
    strong#followers.stat
      = @user.followers.count
    |followers

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 50), current_user
h1= current_user.name
span= link_to "view my profile", current_user
span= pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/about.html.slim
= provide(:title, "About")
h1 About
p
  | The
  a< href="https://www.railstutorial.org/"
    em Ruby on Rails Tutorial
  |, part of the
  a<> href="https://www.learnenough.com/" Learn Enough
  |family of tutorials, is a
  a<> href="https://www.railstutorial.org/book" book
  |and
  a<> href="https://screencasts.railstutorial.org/" screencast series
  |to teach web development with
  a< href="https://rubyonrails.org/" Ruby on Rails
  |. This is the sample app for the tutorial.

app/views/static_pages/contact.html.slim
= provide(:title, "Contact")
h1 Contact
p
  |Contact the Ruby on Rails Tutorial about the sample app at the
  a< href="https://www.railstutorial.org/contact" contact page
  |.

app/views/static_pages/help.html.slim
= provide(:title, "Help")
h1 Help
p
  |Get help on the Ruby on Rails Tutorial at the
  a< href="https://www.railstutorial.org/help" Rails Tutorial Help page
  |. To get help on this sample app, see the
  a< href="https://www.railstutorial.org/book"
    em Ruby on Rails Tutorial
  |.

app/views/static_pages/home.html.slim
= provide(:title, "Home")
- if user_signed_in?
  .row
    aside.col-md-4
      section.user_info
        = render 'shared/user_info'
      section.stats
        = render 'shared/stats'
      section.micropost_form
        = render 'shared/micropost_form'
    .col-md-8
      h3 Micropost Feed
      = render 'shared/feed'
- else
  .center.jumbotron
    h1 Welcome to the Sample App
    h2
      |This is the home page for the
      a<> href="https://www.railstutorial.org/" Ruby on Rails Tutorial
      |sample application.
    = link_to 'Sign up now!', new_user_registration_path, class: 'btn btn-lg btn-primary'
  = link_to image_tag('rails.svg', alt: 'Rails logo', width: '200'), 'https://rubyonrails.org/'

app/views/users/_follow.html.slim
= form_with(model: current_user.active_relationships.build, remote: true) do |f|
  = hidden_field_tag :followed_id, @user.id
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.slim
/- unless current_user?(@user)
- unless current_user
#follow_form
  - if current_user.following?(@user)
    = render 'unfollow'
  - else
    = render 'follow'

app/views/users/_unfollow.html.slim
= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn"

app/views/users/_user.html.slim
li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin && !current_user
    |&nbsp|&nbsp
    = link_to "delete", user, method: :delete,
                                data: { confirm: "You sure?" }

app/views/users/edit.html.slim
= provide(:title, "Edit user")
- provide(:button_text, 'Save changes')
h1 Update your profile
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    .gravatar_edit
      = gravatar_for @user
      a href="https://gravatar.com/emails" target="_blank" change

app/views/users/index.html.slim
= provide(:title, 'All users')
h1 All users
= will_paginate
ul
  .users
    = render @users
= will_paginate

app/views/users/show.html.slim
= provide(:title, @user.name)
.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name
    section.stats
      = render 'shared/stats'
  .col-md-8
    = render 'follow_form' if user_signed_in?
    - if @user.microposts.any?
      h3
        |Microposts (
        = @user.microposts.count
        |)
      ol
        .microposts
          = render @microposts
        = will_paginate @microposts

app/views/users/show_follow.html.slim
= provide(:title, @title)
.row
  aside.col-md-4
    section.user_info
      = gravatar_for @user
      h1= @user.name
      span= link_to "view my profile", @user
      span
        b Microposts:
        = @user.microposts.count
    section.stats
      = render 'shared/stats'
      - if @users.any?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
  .col-md-8
    h3= @title
    - if @users.any?
      ul.users.follow
        = render @users
      = will_paginate